[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Leaderboard"
version = "0.0.4"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
